name: Shopify Sync

on:
  workflow_dispatch:
    inputs:
      cleanup_images:
        description: "Temizlik modu (imzalı resimleri XML'e göre sil)"
        required: false
        default: "false"
        type: choice
        options: ["false","true"]
  schedule:
    - cron: "*/30 * * * *"   # Her 30 dk (UTC)

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install deps
        run: npm ci || npm i

      - name: Run sync
        env:
          SHOP_DOMAIN:           ${{ secrets.SHOP_DOMAIN }}
          SHOPIFY_ACCESS_TOKEN:  ${{ secrets.SHOPIFY_ACCESS_TOKEN }}
          SOURCE_URL:            ${{ secrets.SOURCE_URL }}
          PRIMARY_DOMAIN:        ${{ secrets.PRIMARY_DOMAIN }}
          BATCH_SIZE:            ${{ secrets.BATCH_SIZE }}
          CLEANUP_IMAGES:        ${{ github.event.inputs.cleanup_images }}
        run: node index.mjs
