name: Shopify Sync

on:
  workflow_dispatch:
    inputs:
      cleanup_images:
        description: "Görsel temizliği (imzalı, XML'de olmayanları sil)"
        required: false
        default: "false"
        type: choice
        options: ["false","true"]
      cleanup_variants:
        description: "Varyant temizliği (XML'de olmayanları temizle)"
        required: false
        default: "false"
        type: choice
        options: ["false","true"]
      variant_delete:
        description: "Varyant temizliği yöntemi: true=Sil, false=Stok0+Engel"
        required: false
        default: "false"
        type: choice
        options: ["false","true"]
      diag:
        description: "Teşhis çıktısı (model→renk/beden haritası)"
        required: false
        default: "false"
        type: choice
        options: ["false","true"]
  schedule:
    - cron: "*/30 * * * *"

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '18' }
      - run: npm ci || npm i
      - name: Run sync
        env:
          SHOP_DOMAIN:           ${{ secrets.SHOP_DOMAIN }}
          SHOPIFY_ACCESS_TOKEN:  ${{ secrets.SHOPIFY_ACCESS_TOKEN }}
          SOURCE_URL:            ${{ secrets.SOURCE_URL }}
          BATCH_SIZE:            ${{ secrets.BATCH_SIZE }}
          QPS:                   ${{ secrets.QPS }}
          CLEANUP_IMAGES:        ${{ github.event.inputs.cleanup_images }}
          CLEANUP_VARIANTS:      ${{ github.event.inputs.cleanup_variants }}
          VARIANT_DELETE:        ${{ github.event.inputs.variant_delete }}
          DIAG:                  ${{ github.event.inputs.diag }}
        run: node index.mjs
